fix: conditional env

diff --git a/.github/workflows/deploy-chromatic.yaml b/.github/workflows/deploy-chromatic.yaml
--- a/.github/workflows/deploy-chromatic.yaml
+++ b/.github/workflows/deploy-chromatic.yaml
@@ -2,7 +2,7 @@ name: Chromatic Deployment
 on:
   workflow_call:
     inputs:
-      cromaticToken:
+      env:
         type: string
         required: true
 jobs:
@@ -26,11 +26,25 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-node-
       - run: yarn
+      - name: Set Chromatic Project Token
+        id: set-chromatic-token
+        env:
+          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
+          CHROMATIC_PROJECT_TOKEN_DEV: ${{ secrets.CHROMATIC_PROJECT_TOKEN_DEV }}
+        run: |
+          if ${{ inputs.env }} == 'dev'; then
+            echo "CHROMATIC_PROJECT_TOKEN=$CHROMATIC_PROJECT_TOKEN_DEV" >> "$GITHUB_OUPUT"
+          elif ${{ inputs.env }} == 'main'; then
+            echo "CHROMATIC_PROJECT_TOKEN=$CHROMATIC_PROJECT_TOKEN" >> "$GITHUB_OUPUT"
+          else
+            echo "Error: Invalid environment"
+            exit 1
+          fi
       - name: Run Chromatic
         uses: chromaui/action@latest
         id: chromatic
         with:
-          projectToken: ${{ inputs.cromaticToken }}
+          projectToken: ${{ steps.set-chromatic-token.outputs.CHROMATIC_PROJECT_TOKEN }}
           token: ${{ secrets.GITHUB_TOKEN }}
       - name: comment PR
         uses: actions/github-script@v6
